cli:
- changed-files:
  - any-glob-to-any-file: ['packages/cli/**/*']

core:
- changed-files:
  - any-glob-to-any-file: ['packages/core/**/*']

github-actions:
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/**/*']

dependencies:
- changed-files:
  - any-glob-to-any-file: ['package.json', 'pnpm-lock.yaml', '**/package.json']
