name: CI - Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Build & Test (OS=${{ matrix.os }}, Node=${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Git user
        run: |
          git config user.name "Juhyeok Kang"
          git config user.email "kangju2000@gmail.com"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
      - name: Setup Node.js & pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm type-check

      - name: Build packages
        run: pnpm build

      - name: Test CLI (Node.js)
        run: node packages/cli/dist/index.cjs --version

      - name: Build macOS binary
        if: runner.os == 'macOS'
        run: pnpm --filter "git-intent" pkg:build:macos

      - name: Test macOS binary
        if: runner.os == 'macOS'
        run: |
          chmod +x packages/cli/build/git-intent-macos
          ./packages/cli/build/git-intent-macos --version
